[package]
name = "engine"
version = "0.1.0"
authors = ["olson-dan <olson-dan@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.5"
image = "0.21.2"
byteorder = "1.3.2"